#!/bin/bash

## Description: compiles ts to js
## Usage: javascript
## Example: ddev javascript


cd Build

node_modules/grunt/bin/grunt clear-build && node_modules/grunt/bin/grunt scripts --force

cd ..

cp -r Build/JavaScript/friendsoftypo3/content-blocks-gui packages/content_blocks_gui/Resources/Public/JavaScript

ddev typo3 cache:flush
