services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\ContentBlocks\BackendController\ContentBlocksAjaxController:
    public: true

  TYPO3\CMS\ContentBlocks\BackendController\ContentBlocksController:
    public: true

  TYPO3\CMS\ContentBlocks\Domain\Repository\ContentBlockConfigurationRepository:
    public: true

  TYPO3\CMS\ContentBlocks\Generator\TcaGenerator:
    public: true

  TYPO3\CMS\ContentBlocks\Service\ConfigurationService:
    public: true

  TYPO3\CMS\ContentBlocks\Factory\ContentBlockConfigurationFactory:
    public: true
