services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\ContentBlocks\BackendController\ContentBlocksAjaxController:
    public: true

  TYPO3\CMS\ContentBlocks\BackendController\ContentBlocksController:
    public: true

  TYPO3\CMS\ContentBlocks\Generator\TcaGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-tca'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

  TYPO3\CMS\ContentBlocks\Service\ConfigurationService:
    public: true

  TYPO3\CMS\ContentBlocks\Factory\ContentBlockConfigurationFactory:
    public: true

  TYPO3\CMS\ContentBlocks\Factory\TableDefinitionFactory:
    public: true

  TYPO3\CMS\ContentBlocks\Backend\Preview\PreviewRenderer:
    public: true

  TYPO3\CMS\ContentBlocks\Service\LocalConfRegistrationService:
    public: true

  TYPO3\CMS\ContentBlocks\Generator\SqlGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-sql'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlocksDataProcessor:
    autoconfigure: false
    public: true

  TYPO3\CMS\ContentBlocks\Loader\ComposerLoader:
    tags:
      - name: cb.loader
        identifier: composer

  TYPO3\CMS\ContentBlocks\Loader\LegacyLoader:
    tags:
      - name: cb.loader
        identifier: legacy

  TYPO3\CMS\ContentBlocks\Loader\LoaderFactory:
    public: true

  TYPO3\CMS\ContentBlocks\Loader\LoaderInterface:
    factory:
      - '@TYPO3\CMS\ContentBlocks\Loader\LoaderFactory'
      - 'create'

  TYPO3\CMS\ContentBlocks\Definition\TableDefinitionCollection:
    shared: false
    factory:
      - '@TYPO3\CMS\ContentBlocks\Loader\LoaderFactory'
      - 'load'
