services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\ContentBlocks\:
    resource: '../Classes/*'

  TYPO3\CMS\ContentBlocks\Generator\TcaGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-tca'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent

  TYPO3\CMS\ContentBlocks\Generator\SqlGenerator:
    public: true
    tags:
      - name: event.listener
        identifier: 'content-blocks-sql'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  TYPO3\CMS\ContentBlocks\Backend\Preview\PreviewRenderer:
    public: true

  TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlocksDataProcessor:
    autoconfigure: false
    public: true

  TYPO3\CMS\ContentBlocks\Loader\ComposerLoader:
    tags:
      - name: cb.loader
        identifier: composer

  TYPO3\CMS\ContentBlocks\Loader\LegacyLoader:
    tags:
      - name: cb.loader
        identifier: legacy

  TYPO3\CMS\ContentBlocks\Loader\LoaderFactory:
    public: true

  TYPO3\CMS\ContentBlocks\Loader\LoaderInterface:
    factory:
      - '@TYPO3\CMS\ContentBlocks\Loader\LoaderFactory'
      - 'create'

  TYPO3\CMS\ContentBlocks\Definition\TableDefinitionCollection:
    shared: false
    factory:
      - '@TYPO3\CMS\ContentBlocks\Loader\LoaderFactory'
      - 'load'

  TYPO3\CMS\ContentBlocks\Command\CreateContentBlockCommand:
    tags:
      - name: 'console.command'
        command: 'make:content-block'
        description: 'Create a content block skeleton.'
        schedulable: false
