services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\ContentBlocks\BackendController\ContentBlocksAjaxController:
    public: true

  TYPO3\CMS\ContentBlocks\BackendController\ContentBlocksController:
    public: true

  TYPO3\CMS\ContentBlocks\Domain\Repository\ContentBlockConfigurationRepository:
    public: true

  TYPO3\CMS\ContentBlocks\Generator\TcaGenerator:
    autowire: true
    autoconfigure: false
    public: true

  TYPO3\CMS\ContentBlocks\Service\ConfigurationService:
    autowire: true
    autoconfigure: false
    public: true

  TYPO3\CMS\ContentBlocks\Factory\ContentBlockConfigurationFactory:
    autowire: true
    autoconfigure: false
    public: true

  TYPO3\CMS\ContentBlocks\Factory\TableDefinitionFactory:
    autowire: true
    autoconfigure: false
    public: true

  TYPO3\CMS\ContentBlocks\Definition\TableDefinitionCollection:
    autowire: true
    autoconfigure: false
    public: true

  TYPO3\CMS\ContentBlocks\Backend\Preview\PreviewRenderer:
    autowire: true
    autoconfigure: false
    public: true

  TYPO3\CMS\ContentBlocks\Generator\SqlGenerator:
    autowire: true
    autoconfigure: false
    public: true
    tags:
      - name: event.listener
        identifier: 'cb-sql-generator'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
        method: addDatabaseTablesDefinition

  TYPO3\CMS\ContentBlocks\DataProcessing\ContentBlocksDataProcessor:
    autowire: true
    autoconfigure: false
    public: true
